# -*- coding: utf-8 -*-
"""reviews-data-input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umJChYchNIuz-L02cvpv1FrQBrCoRwuI
"""

import pandas as pd

## Google Colab- Google Drive connectionsinstructions 

# This step needs to be done for the first time when you're reading something from the Shared Project Folder 
# Please navigate to "Shared with me" on your Gdrive home sceen
# Right click on the "NLP-Group1-FinalProj" (the primary folder for this project) and select "Add shortcut to Drive"
# This way the below code can find a link to the Project drive folder through your own drive.


# Mounting your personal Gdrive to the Colab notebook
from google.colab import drive
drive.mount('/gdrive',force_remount=True)

"""## Cleaning Gourmet and Groceries reviews"""

# Reading Amazon reviews data from a compressed json file to pandas dataframe 
groc_data = pd.read_json("/gdrive/My Drive/NLP-Group1-FinalProj/Data/reviews_Grocery_and_Gourmet_Food.json.gz", lines=True, compression="gzip")

#Dropping columns that are not required
groc_data = groc_data.drop(columns= ["reviewerID","reviewerName","asin", "helpful","reviewTime"])
groc_data.columns= ["review_text","rating","review_headline","unix_timestamp"]

# Adding product category as a column
groc_data["product_category"] = "Grocery and Gourmet Food"

# Rearranging columns
groc_data = groc_data[['unix_timestamp', 'product_category', 'review_headline', 'rating', 'review_text']]

# Writing the dataframe to Data folder as a csv
groc_data.to_csv('/gdrive/My Drive/NLP-Group1-FinalProj/Data/groc_amz_rev.csv', index=False)

"""## Cleaning "Home and Kitchen" reviews"""

# Reading Amazon reviews data from a compressed json file to pandas dataframe 
home_data = pd.read_json("/gdrive/My Drive/NLP-Group1-FinalProj/Data/reviews_Home_and_Kitchen.json.gz", lines=True, compression="gzip")

#Dropping columns that are not required
home_data = home_data.drop(columns= ["reviewerID","reviewerName","asin", "helpful","reviewTime"])
home_data.columns= ["review_text","rating","review_headline","unix_timestamp"]

# Adding product category as a column
home_data["product_category"] = "Home and Kitchen"

# Rearranging columns
home_data = home_data[['unix_timestamp', 'product_category', 'review_headline', 'rating', 'review_text']]